table GuestSatisfaction
	lineageTag: 780a9bc4-0eaa-40b7-88d3-7f92076c7eca
	sourceLineageTag: [fact].[GuestSatisfaction]

	measure 'Survey Count' = COUNTROWS(GuestSatisfaction)
		formatString: #,0
		displayFolder: measures\base\volume
		lineageTag: 9ced93b0-6a97-4997-9426-55b6109c40c8

	measure 'Avg Satisfaction Score' = AVERAGE(GuestSatisfaction[SatisfactionScore])
		formatString: 0.00
		displayFolder: measures\base\survey
		lineageTag: ba1d3f49-2c65-470a-b532-535ebdea34e4

	measure 'Avg Service Score' = AVERAGE(GuestSatisfaction[ServiceScore])
		formatString: 0.00
		displayFolder: measures\base\survey
		lineageTag: c1ce02f0-449f-400e-bcdc-f86f633bfd9d

	measure 'Avg Cleanliness Score' = AVERAGE(GuestSatisfaction[CleanlinessScore])
		formatString: 0.00
		displayFolder: measures\base\survey
		lineageTag: 5b106730-d4ba-4ab2-94dc-1cfe18693ff1

	measure 'Avg Value Score' = AVERAGE(GuestSatisfaction[ValueScore])
		formatString: 0.00
		displayFolder: measures\base\survey
		lineageTag: d1bc0bee-94a4-4c1a-928b-fb34b9f20665

	measure 'Recommend Count' = CALCULATE([Survey Count], GuestSatisfaction[WouldRecommend] = TRUE())
		formatString: #,0
		displayFolder: measures\base\survey
		lineageTag: efc6a881-33c0-4f85-b5a8-0b3f032caa7d

	measure 'Recommend %' = DIVIDE([Recommend Count], [Survey Count])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: measures\base\survey
		lineageTag: b7a0d877-0e47-4ec9-a5cb-25d04da6dbc7

	column SurveyKey
		dataType: int64
		formatString: 0
		displayFolder: keys
		lineageTag: efb85986-17ee-40ca-9808-7eb7e084c88b
		sourceLineageTag: SurveyKey
		summarizeBy: none
		sourceColumn: SurveyKey

		annotation SummarizationSetBy = Automatic

	column StayDateKey
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		displayFolder: keys
		lineageTag: 1f35bc37-f7ec-4317-81c4-1eb05e01ebac
		sourceLineageTag: StayDateKey
		summarizeBy: none
		sourceColumn: StayDateKey

		annotation SummarizationSetBy = Automatic

	column PropertyKey
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		displayFolder: keys
		lineageTag: c7ccfec9-1926-4390-8607-0b69db113310
		sourceLineageTag: PropertyKey
		summarizeBy: none
		sourceColumn: PropertyKey

		annotation SummarizationSetBy = Automatic

	column GuestKey
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		displayFolder: keys
		lineageTag: ecc6268f-3fa7-42ca-9341-05aa2155be46
		sourceLineageTag: GuestKey
		summarizeBy: none
		sourceColumn: GuestKey

		annotation SummarizationSetBy = Automatic

	column ChannelKey
		dataType: int64
		isHidden
		formatString: 0
		isAvailableInMdx: false
		displayFolder: keys
		lineageTag: 2fdc8118-634f-4350-a479-99b2cb621df4
		sourceLineageTag: ChannelKey
		summarizeBy: none
		sourceColumn: ChannelKey

		annotation SummarizationSetBy = Automatic

	column SatisfactionScore
		dataType: decimal
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: fact
		lineageTag: 8235592d-0213-4642-88ba-b3a02ba702f1
		sourceLineageTag: SatisfactionScore
		summarizeBy: none
		sourceColumn: SatisfactionScore

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ServiceScore
		dataType: decimal
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: fact
		lineageTag: b9292f8a-c40e-43ed-a363-8e55ee4ae606
		sourceLineageTag: ServiceScore
		summarizeBy: none
		sourceColumn: ServiceScore

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column CleanlinessScore
		dataType: decimal
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: fact
		lineageTag: 3a3059c0-bdde-439a-9c50-98155a0d2266
		sourceLineageTag: CleanlinessScore
		summarizeBy: none
		sourceColumn: CleanlinessScore

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ValueScore
		dataType: decimal
		isHidden
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: fact
		lineageTag: 3e0481ff-74a3-41bc-9c5d-44fb7d7f94a6
		sourceLineageTag: ValueScore
		summarizeBy: none
		sourceColumn: ValueScore

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column WouldRecommend
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		displayFolder: fact
		lineageTag: 749570ac-8d6b-4ced-a10d-268580bf4a0e
		sourceLineageTag: WouldRecommend
		summarizeBy: none
		sourceColumn: WouldRecommend

		annotation SummarizationSetBy = Automatic

	partition GuestSatisfaction = entity
		mode: directLake
		source
			entityName: GuestSatisfaction
			schemaName: fact
			expressionSource: 'DirectLake - lh_thecubemodel'

	annotation TabularEditor_TableGroup = Fact

